# LABORATORY

Carga y visualización de los datasets de laboratorio.

In [1]:
%load_ext kedro.ipython

[06/05/26 14:47:06] INFO     Using                                                                  ]8;id=9637976;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=9637977;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\framework\project\__init__.py#281\281]8;;\
                             'C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages
                             \kedro\framework\project\rich_logging.yml' as logging configuration.

                    INFO     Registered line magic '%reload_kedro'                                   ]8;id=9637984;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=9637985;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py#67\67]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=9637991;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=9637992;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py#69\69]8;;\

                    INFO     Resolved project path as:                                              ]8;id=9637998;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=9637999;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py#193\193]8;;\
                             C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes.
                             To set a different path, run '%reload_kedro <project_root>'

[06/05/26 14:47:06] INFO     No typed parameter requirements found, returning original   ]8;id=9638006;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\validation\parameter_validator.py\parameter_validator.py]8;;\:]8;id=9638007;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\validation\parameter_validator.py#124\124]8;;\
                             parameters

[06/05/26 14:47:07] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=9638014;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=9638015;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro_telemetry\plugin.py#273\273]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

[06/05/26 14:47:08] INFO     Kedro project Nhanes                                                   ]8;id=9638021;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=9638022;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py#159\159]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=9638028;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=9638029;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py#160\160]8;;\
                             'pipelines'

## BIOPRO_J (Standard Biochemistry)

In [2]:
df = catalog.load("biopro_j_dataset")
df

                    INFO     Loading data from biopro_j_dataset (GenericDataset)...            ]8;id=9638036;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=9638037;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,LBXSATSI,LBDSATLC,LBXSAL,LBDSALSI,LBXSAPSI,LBXSASSI,LBXSC3SI,LBXSBU,LBDSBUSI,...,LBXSCA,LBDSCASI,LBXSCH,LBDSCHSI,LBXSTP,LBDSTPSI,LBXSTR,LBDSTRSI,LBXSUA,LBDSUASI
0,93705.0,16.0,5.397605e-79,4.4,44.0,74.0,20.0,31.0,11.0,3.93,...,9.2,2.300,157.0,4.060,7.3,73.0,95.0,1.073,5.8,345.0
1,93706.0,10.0,5.397605e-79,4.4,44.0,79.0,14.0,28.0,12.0,4.28,...,9.6,2.400,149.0,3.853,7.1,71.0,92.0,1.039,8.0,475.8
2,93707.0,13.0,5.397605e-79,5.2,52.0,238.0,24.0,22.0,17.0,6.07,...,10.1,2.525,199.0,5.146,8.0,80.0,110.0,1.242,5.5,327.1
3,93708.0,19.0,5.397605e-79,3.9,39.0,66.0,21.0,27.0,16.0,5.71,...,9.5,2.375,210.0,5.431,7.1,71.0,72.0,0.813,4.5,267.7
4,93709.0,15.0,5.397605e-79,3.7,37.0,86.0,17.0,24.0,20.0,7.14,...,9.9,2.475,180.0,4.655,7.0,70.0,132.0,1.490,6.2,368.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6396,102952.0,22.0,5.397605e-79,4.8,48.0,57.0,27.0,27.0,13.0,4.64,...,9.9,2.475,121.0,3.129,7.4,74.0,98.0,1.106,6.4,380.7
6397,102953.0,40.0,5.397605e-79,4.0,40.0,115.0,29.0,24.0,17.0,6.07,...,9.0,2.250,184.0,4.758,7.5,75.0,114.0,1.287,5.8,345.0
6398,102954.0,6.0,5.397605e-79,3.9,39.0,55.0,15.0,21.0,8.0,2.86,...,9.0,2.250,172.0,4.448,6.5,65.0,64.0,0.723,3.1,184.4
6399,102955.0,11.0,5.397605e-79,4.1,41.0,84.0,16.0,23.0,11.0,3.93,...,9.2,2.300,151.0,3.905,7.5,75.0,89.0,1.005,6.3,374.7
6400,102956.0,47.0,5.397605e-79,4.3,43.0,84.0,27.0,27.0,12.0,4.28,...,9.7,2.425,167.0,4.319,7.2,72.0,289.0,3.263,6.4,380.7

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## CBC_J (Complete Blood Count)

In [3]:
df = catalog.load("cbc_j_dataset")
df

                    INFO     Loading data from cbc_j_dataset (GenericDataset)...               ]8;id=9638042;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=9638043;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,LBXWBCSI,LBXLYPCT,LBXMOPCT,LBXNEPCT,LBXEOPCT,LBXBAPCT,LBDLYMNO,LBDMONO,LBDNENO,...,LBXRBCSI,LBXHGB,LBXHCT,LBXMCVSI,LBXMCHSI,LBXMC,LBXRDW,LBXPLTSI,LBXMPSI,LBXNRBC
0,93703.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93704.0,7.4,47.8,8.0,42.6,1.0,0.7,3.5,0.6,3.2,...,4.25,13.1,37.0,87.0,30.8,35.4,12.8,239.0,8.6,1.000000e-01
2,93705.0,8.6,40.0,7.4,48.8,2.9,1.0,3.4,0.6,4.2,...,5.48,11.9,36.7,67.0,21.7,32.4,15.6,309.0,7.9,5.397605e-79
3,93706.0,6.1,24.6,9.1,61.4,4.3,0.8,1.5,0.6,3.7,...,5.24,16.3,47.0,89.7,31.1,34.7,12.2,233.0,6.6,5.397605e-79
4,93707.0,11.2,37.1,6.2,54.7,1.6,0.5,4.2,0.7,6.1,...,5.02,14.5,42.1,83.9,28.9,34.4,13.6,348.0,8.5,2.000000e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8361,102952.0,5.1,34.9,7.1,56.2,1.3,0.6,1.8,0.4,2.9,...,4.64,13.4,40.6,87.7,29.0,33.1,13.3,161.0,9.1,5.000000e-01
8362,102953.0,8.3,28.3,6.8,60.8,3.6,0.6,2.3,0.6,5.0,...,5.01,15.5,44.4,88.8,30.9,34.8,13.6,227.0,8.7,1.000000e-01
8363,102954.0,5.1,43.5,11.8,39.9,3.5,1.4,2.2,0.6,2.0,...,3.72,6.4,23.1,61.9,17.3,27.9,19.6,145.0,9.7,1.000000e-01
8364,102955.0,11.4,33.4,7.3,57.5,1.1,0.9,3.8,0.8,6.6,...,4.93,11.4,33.7,68.4,23.1,33.7,17.4,382.0,7.7,1.000000e-01
8365,102956.0,9.0,29.4,6.9,58.8,4.0,1.0,2.6,0.6,5.3,...,5.46,17.4,50.1,91.8,31.9,34.7,13.3,159.0,8.5,5.397605e-79

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## HSCRP_J (hs-CRP)

In [4]:
df = catalog.load("hscrp_j_dataset")
df

                    INFO     Loading data from hscrp_j_dataset (GenericDataset)...             ]8;id=9638048;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=9638049;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

          SEQN  LBXHSCRP      LBDHRPLC
0      93703.0       NaN           NaN
1      93704.0      0.29  5.397605e-79
2      93705.0      2.72  5.397605e-79
3      93706.0      0.74  5.397605e-79
4      93707.0      0.32  5.397605e-79
...        ...       ...           ...
8361  102952.0      0.45  5.397605e-79
8362  102953.0      1.84  5.397605e-79
8363  102954.0      0.81  5.397605e-79
8364  102955.0      5.11  5.397605e-79
8365  102956.0      3.70  5.397605e-79

[8366 rows x 3 columns]

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## GHB_J (Glycohemoglobin / HbA1c)

In [5]:
df = catalog.load("ghb_j_dataset")
df

                    INFO     Loading data from ghb_j_dataset (GenericDataset)...               ]8;id=9638054;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=9638055;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

          SEQN  LBXGH
0      93705.0    6.2
1      93706.0    5.2
2      93707.0    5.6
3      93708.0    6.2
4      93709.0    6.3
...        ...    ...
6396  102952.0    7.4
6397  102953.0    5.9
6398  102954.0    5.2
6399  102955.0    5.5
6400  102956.0    5.4

[6401 rows x 2 columns]

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## HDL_J (HDL Cholesterol)

In [6]:
df = catalog.load("hdl_j_dataset")
df

                    INFO     Loading data from hdl_j_dataset (GenericDataset)...               ]8;id=9638060;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=9638061;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

          SEQN  LBDHDD  LBDHDDSI
0      93705.0    60.0      1.55
1      93706.0    47.0      1.22
2      93707.0    68.0      1.76
3      93708.0    88.0      2.28
4      93709.0    65.0      1.68
...        ...     ...       ...
7430  102952.0    60.0      1.55
7431  102953.0    49.0      1.27
7432  102954.0    54.0      1.40
7433  102955.0    34.0      0.88
7434  102956.0    34.0      0.88

[7435 rows x 3 columns]

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## TCHOL_J (Total Cholesterol)

In [7]:
df = catalog.load("tchol_j_dataset")
df

                    INFO     Loading data from tchol_j_dataset (GenericDataset)...             ]8;id=9638066;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=9638067;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

          SEQN  LBXTC  LBDTCSI
0      93705.0  157.0     4.06
1      93706.0  148.0     3.83
2      93707.0  189.0     4.89
3      93708.0  209.0     5.40
4      93709.0  176.0     4.55
...        ...    ...      ...
7430  102952.0  119.0     3.08
7431  102953.0  182.0     4.71
7432  102954.0  172.0     4.45
7433  102955.0  150.0     3.88
7434  102956.0  163.0     4.22

[7435 rows x 3 columns]

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## ALB_CR_J (Albumin & Creatinine - Urine)

In [8]:
df = catalog.load("alb_cr_j_dataset")
df

                    INFO     Loading data from alb_cr_j_dataset (GenericDataset)...            ]8;id=9638072;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=9638073;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,URXUMA,URXUMS,URDUMALC,URXUCR,URXCRS,URDUCRLC,URDACT
0,93705.0,3.2,3.2,5.397605e-79,24.0,2121.6,5.397605e-79,13.33
1,93706.0,39.6,39.6,5.397605e-79,69.0,6099.6,5.397605e-79,57.39
2,93707.0,41.6,41.6,5.397605e-79,209.0,18475.6,5.397605e-79,19.90
3,93708.0,9.1,9.1,5.397605e-79,47.0,4154.8,5.397605e-79,19.36
4,93709.0,26.4,26.4,5.397605e-79,215.0,19006.0,5.397605e-79,12.28
...,...,...,...,...,...,...,...,...
7931,102952.0,5.3,5.3,5.397605e-79,51.0,4508.4,5.397605e-79,10.39
7932,102953.0,10.2,10.2,5.397605e-79,231.0,20420.4,5.397605e-79,4.42
7933,102954.0,3.4,3.4,5.397605e-79,31.0,2740.4,5.397605e-79,10.97
7934,102955.0,83.2,83.2,5.397605e-79,177.0,15646.8,5.397605e-79,47.01
7935,102956.0,53.2,53.2,5.397605e-79,75.0,6630.0,5.397605e-79,70.93

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## COT_J (Cotinine - Serum)

In [9]:
df = catalog.load("cot_j_dataset")
df

                    INFO     Loading data from cot_j_dataset (GenericDataset)...               ]8;id=9638078;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=9638079;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

          SEQN   LBXCOT      LBDCOTLC  LBXHCT      LBDHCTLC
0      93705.0    0.028  5.397605e-79   0.020  5.397605e-79
1      93706.0    0.138  5.397605e-79   0.024  5.397605e-79
2      93707.0    0.555  5.397605e-79   0.070  5.397605e-79
3      93708.0    0.011  1.000000e+00   0.011  1.000000e+00
4      93709.0   54.300  5.397605e-79   0.628  5.397605e-79
...        ...      ...           ...     ...           ...
7931  102952.0    0.085  5.397605e-79   0.015  5.397605e-79
7932  102953.0    0.060  5.397605e-79   0.011  1.000000e+00
7933  102954.0    0.091  5.397605e-79   0.025  5.397605e-79
7934  102955.0    0.020  5.397605e-79   0.011  1.000000e+00
7935  102956.0  327.000  5.397605e-79  99.100  5.397605e-79

[7936 rows x 5 columns]

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## VID_J (Vitamin D)

In [10]:
df = catalog.load("vid_j_dataset")
df

                    INFO     Loading data from vid_j_dataset (GenericDataset)...               ]8;id=9638084;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=9638085;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,LBXVIDMS,LBDVIDLC,LBXVD2MS,LBDVD2LC,LBXVD3MS,LBDVD3LC,LBXVE3MS,LBDVE3LC
0,93703.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93704.0,74.4,5.397605e-79,1.45,1.0,73.0,5.397605e-79,5.84,5.397605e-79
2,93705.0,89.9,5.397605e-79,1.45,1.0,88.5,5.397605e-79,6.16,5.397605e-79
3,93706.0,53.8,5.397605e-79,1.45,1.0,52.4,5.397605e-79,2.70,5.397605e-79
4,93707.0,58.2,5.397605e-79,1.45,1.0,56.8,5.397605e-79,2.93,5.397605e-79
...,...,...,...,...,...,...,...,...,...
8361,102952.0,82.7,5.397605e-79,1.45,1.0,81.3,5.397605e-79,5.43,5.397605e-79
8362,102953.0,49.5,5.397605e-79,1.45,1.0,48.1,5.397605e-79,2.73,5.397605e-79
8363,102954.0,50.5,5.397605e-79,1.45,1.0,49.1,5.397605e-79,2.97,5.397605e-79
8364,102955.0,61.9,5.397605e-79,1.45,1.0,60.5,5.397605e-79,3.97,5.397605e-79
8365,102956.0,58.9,5.397605e-79,1.45,1.0,57.5,5.397605e-79,4.44,5.397605e-79

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## PBCD_J (Lead, Cadmium, Mercury - Blood)

In [11]:
df = catalog.load("pbcd_j_dataset")
df

                    INFO     Loading data from pbcd_j_dataset (GenericDataset)...              ]8;id=9638090;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=9638091;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,LBXBPB,LBDBPBSI,LBDBPBLC,LBXBCD,LBDBCDSI,LBDBCDLC,LBXTHG,LBDTHGSI,LBDTHGLC,LBXBSE,LBDBSESI,LBDBSELC,LBXBMN,LBDBMNSI,LBDBMNLC
0,93703.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93704.0,NaN,NaN,NaN,0.07,0.62,1.000000e+00,0.47,2.35,5.397605e-79,142.28,1.81,5.397605e-79,9.41,171.28,5.397605e-79
2,93705.0,2.98,0.14,5.397605e-79,0.24,2.14,5.397605e-79,1.07,5.34,5.397605e-79,185.71,2.36,5.397605e-79,8.57,155.99,5.397605e-79
3,93706.0,0.74,0.04,5.397605e-79,0.21,1.87,5.397605e-79,10.64,53.09,5.397605e-79,199.44,2.53,5.397605e-79,14.07,256.10,5.397605e-79
4,93707.0,0.39,0.02,5.397605e-79,0.14,1.25,5.397605e-79,0.20,1.00,1.000000e+00,179.34,2.28,5.397605e-79,12.60,229.35,5.397605e-79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8361,102952.0,0.75,0.04,5.397605e-79,0.61,5.43,5.397605e-79,0.65,3.24,5.397605e-79,164.18,2.09,5.397605e-79,16.81,305.98,5.397605e-79
8362,102953.0,1.12,0.05,5.397605e-79,0.21,1.87,5.397605e-79,0.62,3.09,5.397605e-79,195.21,2.48,5.397605e-79,8.34,151.80,5.397605e-79
8363,102954.0,0.46,0.02,5.397605e-79,0.32,2.85,5.397605e-79,2.08,10.38,5.397605e-79,164.46,2.09,5.397605e-79,8.76,159.45,5.397605e-79
8364,102955.0,0.25,0.01,5.397605e-79,0.11,0.98,5.397605e-79,0.20,1.00,1.000000e+00,184.00,2.34,5.397605e-79,21.76,396.08,5.397605e-79
8365,102956.0,0.90,0.04,5.397605e-79,3.96,35.23,5.397605e-79,0.83,4.14,5.397605e-79,233.65,2.97,5.397605e-79,6.14,111.76,5.397605e-79

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)