# QUESTIONNAIRE

Carga y visualización de los datasets de cuestionario.

In [1]:
%load_ext kedro.ipython

[06/05/26 14:47:13] INFO     Using                                                                  ]8;id=13771002;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=13771003;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\framework\project\__init__.py#281\281]8;;\
                             'C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages
                             \kedro\framework\project\rich_logging.yml' as logging configuration.

                    INFO     Registered line magic '%reload_kedro'                                   ]8;id=13771010;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=13771011;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py#67\67]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=13771017;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=13771018;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py#69\69]8;;\

                    INFO     Resolved project path as:                                              ]8;id=13771024;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=13771025;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py#193\193]8;;\
                             C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes.
                             To set a different path, run '%reload_kedro <project_root>'

[06/05/26 14:47:14] INFO     No typed parameter requirements found, returning original   ]8;id=13771032;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\validation\parameter_validator.py\parameter_validator.py]8;;\:]8;id=13771033;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\validation\parameter_validator.py#124\124]8;;\
                             parameters

                    INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=13771040;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=13771041;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro_telemetry\plugin.py#273\273]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

[06/05/26 14:47:15] INFO     Kedro project Nhanes                                                   ]8;id=13771047;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=13771048;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py#159\159]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=13771054;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=13771055;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py#160\160]8;;\
                             'pipelines'

## SMQ_J (Smoking - Cigarette Use)

In [2]:
df = catalog.load("smq_j_dataset")
df

                    INFO     Loading data from smq_j_dataset (GenericDataset)...               ]8;id=13771062;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=13771063;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,SMQ020,SMD030,SMQ040,SMQ050Q,SMQ050U,SMD057,SMQ078,SMD641,SMD650,...,SMQ848,SMQ852Q,SMQ852U,SMQ890,SMQ895,SMQ900,SMQ905,SMQ910,SMQ915,SMAQUEX2
0,93705.0,1.0,16.0,3.0,30.0,4.0,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,NaN,1.0
1,93706.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,NaN,1.0
2,93707.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
3,93708.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,NaN,1.0
4,93709.0,1.0,15.0,1.0,NaN,NaN,NaN,1.0,30.0,5.0,...,NaN,NaN,NaN,1.0,5.397605e-79,1.0,5.397605e-79,1.0,5.397605e-79,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6719,102952.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,NaN,1.0
6720,102953.0,1.0,20.0,3.0,9.0,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,5.397605e-79,1.0,5.397605e-79,1.0,5.397605e-79,1.0
6721,102954.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,NaN,1.0
6722,102955.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
6723,102956.0,1.0,16.0,1.0,NaN,NaN,NaN,2.0,30.0,20.0,...,1.0,2.0,1.0,2.0,NaN,2.0,NaN,1.0,5.397605e-79,1.0

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## ALQ_J (Alcohol Use)

In [3]:
df = catalog.load("alq_j_dataset")
df

                    INFO     Loading data from alq_j_dataset (GenericDataset)...               ]8;id=13771068;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=13771069;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,ALQ111,ALQ121,ALQ130,ALQ142,ALQ270,ALQ280,ALQ290,ALQ151,ALQ170
0,93705.0,1.0,7.000000e+00,1.0,5.397605e-79,NaN,NaN,NaN,2.0,5.000000e+00
1,93706.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93708.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,93709.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,93711.0,1.0,5.000000e+00,1.0,5.397605e-79,NaN,NaN,NaN,2.0,5.397605e-79
...,...,...,...,...,...,...,...,...,...,...
5528,102949.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5529,102952.0,1.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN,2.0,NaN
5530,102953.0,1.0,6.000000e+00,12.0,6.000000e+00,5.397605e-79,6.000000e+00,5.397605e-79,2.0,5.397605e-79
5531,102954.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5532,102956.0,1.0,8.000000e+00,2.0,1.000000e+01,5.397605e-79,5.397605e-79,NaN,2.0,5.397605e-79

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## HSQ_J (Current Health Status)

In [4]:
df = catalog.load("hsq_j_dataset")
df

                    INFO     Loading data from hsq_j_dataset (GenericDataset)...               ]8;id=13771074;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=13771075;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,HSD010,HSQ500,HSQ510,HSQ520,HSQ571,HSQ580,HSQ590,HSAQUEX
0,93703.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,93704.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,1.0
2,93705.0,3.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0
3,93706.0,2.0,2.0,2.0,2.0,1.0,5.0,2.0,2.0
4,93707.0,3.0,2.0,2.0,2.0,NaN,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...
8361,102952.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0
8362,102953.0,4.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0
8363,102954.0,3.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0
8364,102955.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,2.0
8365,102956.0,3.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## PAQ_J (Physical Activity)

In [5]:
df = catalog.load("paq_j_dataset")
df

                    INFO     Loading data from paq_j_dataset (GenericDataset)...               ]8;id=13771080;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=13771081;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,PAQ605,PAQ610,PAD615,PAQ620,PAQ625,PAD630,PAQ635,PAQ640,PAD645,PAQ650,PAQ655,PAD660,PAQ665,PAQ670,PAD675,PAD680
0,93705.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,1.0,2.0,60.0,300.0
1,93706.0,2.0,NaN,NaN,2.0,NaN,NaN,1.0,5.0,45.0,2.0,NaN,NaN,1.0,2.0,30.0,240.0
2,93708.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,1.0,5.0,30.0,120.0
3,93709.0,2.0,NaN,NaN,1.0,2.0,180.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,600.0
4,93711.0,2.0,NaN,NaN,2.0,NaN,NaN,1.0,5.0,60.0,1.0,4.0,60.0,1.0,2.0,30.0,420.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5851,102950.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,60.0
5852,102952.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,1.0,6.0,60.0,120.0
5853,102953.0,1.0,3.0,240.0,1.0,3.0,240.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,360.0
5854,102954.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,1.0,2.0,30.0,600.0
5855,102956.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,720.0

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## PFQ_J (Physical Functioning)

In [6]:
df = catalog.load("pfq_j_dataset")
df

                    INFO     Loading data from pfq_j_dataset (GenericDataset)...               ]8;id=13771086;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=13771087;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,PFQ020,PFQ030,PFQ033,PFQ041,PFQ049,PFQ051,PFQ054,PFQ057,PFQ059,...,PFQ061Q,PFQ061R,PFQ061S,PFQ061T,PFQ063A,PFQ063B,PFQ063C,PFQ063D,PFQ063E,PFQ090
0,93705.0,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,...,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
1,93706.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93707.0,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,93708.0,NaN,NaN,NaN,NaN,1.0,1.0,2.0,1.0,NaN,...,1.0,1.0,1.0,1.0,10.0,11.0,20.0,NaN,NaN,2.0
4,93709.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,NaN,...,2.0,4.0,1.0,2.0,10.0,14.0,20.0,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8416,102952.0,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,...,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
8417,102953.0,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
8418,102954.0,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,NaN,...,1.0,1.0,1.0,2.0,28.0,NaN,NaN,NaN,NaN,2.0
8419,102955.0,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8420,102956.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,NaN,...,2.0,2.0,1.0,2.0,10.0,17.0,28.0,NaN,NaN,2.0

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## DPQ_J (Mental Health - Depression / PHQ-9)

In [7]:
df = catalog.load("dpq_j_dataset")
df

                    INFO     Loading data from dpq_j_dataset (GenericDataset)...               ]8;id=13771092;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=13771093;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,DPQ100
0,93705.0,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,NaN
1,93706.0,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,NaN
2,93708.0,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,NaN
3,93709.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,93711.0,1.000000e+00,5.397605e-79,1.000000e+00,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
...,...,...,...,...,...,...,...,...,...,...,...
5528,102949.0,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,NaN
5529,102952.0,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,NaN
5530,102953.0,1.000000e+00,1.000000e+00,5.397605e-79,1.000000e+00,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,1.000000e+00
5531,102954.0,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,NaN
5532,102956.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,5.397605e-79,5.397605e-79,1.000000e+00

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## SLQ_J (Sleep Disorders)

In [8]:
df = catalog.load("slq_j_dataset")
df

                    INFO     Loading data from slq_j_dataset (GenericDataset)...               ]8;id=13771098;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=13771099;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,SLQ300,SLQ310,SLD012,SLQ320,SLQ330,SLD013,SLQ030,SLQ040,SLQ050,SLQ120
0,93705.0,b'23:00',b'07:00',8.0,b'23:00',b'07:00',8.0,2.000000e+00,5.397605e-79,2.0,5.397605e-79
1,93706.0,b'23:30',b'10:00',10.5,b'00:30',b'12:00',11.5,1.000000e+00,5.397605e-79,2.0,1.000000e+00
2,93708.0,b'22:30',b'06:30',8.0,b'22:30',b'06:30',8.0,9.000000e+00,5.397605e-79,2.0,2.000000e+00
3,93709.0,b'22:30',b'05:30',7.0,b'22:30',b'05:00',6.5,1.000000e+00,5.397605e-79,2.0,1.000000e+00
4,93711.0,b'22:00',b'05:00',7.0,b'23:00',b'08:00',9.0,2.000000e+00,1.000000e+00,1.0,3.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
6156,102950.0,b'03:00',b'10:00',7.0,b'22:00',b'09:00',11.0,1.000000e+00,1.000000e+00,2.0,2.000000e+00
6157,102952.0,b'22:30',b'07:00',8.5,b'22:30',b'07:00',8.5,5.397605e-79,5.397605e-79,2.0,5.397605e-79
6158,102953.0,b'22:00',b'04:00',6.0,b'23:00',b'04:00',5.0,5.397605e-79,1.000000e+00,1.0,2.000000e+00
6159,102954.0,b'22:00',b'06:00',8.0,b'00:00',b'07:00',7.0,1.000000e+00,5.397605e-79,2.0,1.000000e+00
6160,102956.0,b'23:00',b'07:00',8.0,b'02:00',b'09:00',7.0,5.397605e-79,5.397605e-79,1.0,1.000000e+00

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## MCQ_J (Medical Conditions)

In [9]:
df = catalog.load("mcq_j_dataset")
df

                    INFO     Loading data from mcq_j_dataset (GenericDataset)...               ]8;id=13771104;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=13771105;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,MCQ010,MCQ025,MCQ035,MCQ040,MCQ050,AGQ030,MCQ053,MCQ080,MCQ092,...,MCQ300A,MCQ366A,MCQ366B,MCQ366C,MCQ366D,MCQ371A,MCQ371B,MCQ371C,MCQ371D,OSQ230
0,93703.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93704.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93705.0,1.0,10.0,2.0,NaN,NaN,NaN,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0
3,93706.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,...,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN
4,93707.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8892,102952.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0
8893,102953.0,1.0,42.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,...,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0
8894,102954.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,...,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0
8895,102955.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8896,102956.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## DIQ_J (Diabetes)

In [10]:
df = catalog.load("diq_j_dataset")
df

                    INFO     Loading data from diq_j_dataset (GenericDataset)...               ]8;id=13771110;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=13771111;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,DIQ010,DID040,DIQ160,DIQ170,DIQ172,DIQ175A,DIQ175B,DIQ175C,DIQ175D,...,DIQ300D,DID310S,DID310D,DID320,DID330,DID341,DID350,DIQ350U,DIQ360,DIQ080
0,93703.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93704.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93705.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,93706.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,93707.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8892,102952.0,3.0,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8893,102953.0,2.0,NaN,1.0,2.0,1.0,NaN,11.0,NaN,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8894,102954.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8895,102955.0,2.0,NaN,2.0,2.0,1.0,NaN,11.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8896,102956.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## BPQ_J (Blood Pressure & Cholesterol)

In [11]:
df = catalog.load("bpq_j_dataset")
df

                    INFO     Loading data from bpq_j_dataset (GenericDataset)...               ]8;id=13771116;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=13771117;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,BPQ020,BPQ030,BPD035,BPQ040A,BPQ050A,BPQ080,BPQ060,BPQ070,BPQ090D,BPQ100D
0,93705.0,1.0,1.0,50.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN
1,93706.0,2.0,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,NaN
2,93708.0,1.0,1.0,50.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0
3,93709.0,1.0,1.0,71.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN
4,93711.0,2.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
6156,102950.0,1.0,2.0,40.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0
6157,102952.0,2.0,NaN,NaN,NaN,NaN,2.0,1.0,1.0,2.0,NaN
6158,102953.0,2.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,2.0,NaN
6159,102954.0,2.0,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,NaN
6160,102956.0,1.0,1.0,37.0,2.0,NaN,2.0,1.0,4.0,2.0,NaN

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## KIQ_U_J (Kidney Conditions - Urology)

In [12]:
df = catalog.load("kiq_u_j_dataset")
df

                    INFO     Loading data from kiq_u_j_dataset (GenericDataset)...             ]8;id=13771122;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=13771123;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,KIQ022,KIQ025,KIQ026,KIQ029,KIQ005,KIQ010,KIQ042,KIQ430,KIQ044,KIQ450,KIQ046,KIQ470,KIQ050,KIQ052,KIQ480
0,93705.0,2.0,NaN,2.0,NaN,1.0,NaN,1.0,1.0,1.0,1.0,2.0,NaN,1.0,1.0,2.000000e+00
1,93708.0,2.0,NaN,2.0,NaN,3.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1.0,1.0,3.000000e+00
2,93709.0,2.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,93711.0,2.0,NaN,2.0,NaN,1.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,NaN,NaN,3.000000e+00
4,93713.0,2.0,NaN,2.0,NaN,1.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,NaN,NaN,5.397605e-79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5564,102950.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5565,102952.0,2.0,NaN,2.0,NaN,1.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,NaN,NaN,5.397605e-79
5566,102953.0,2.0,NaN,2.0,NaN,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,1.0,1.0,5.397605e-79
5567,102954.0,2.0,NaN,2.0,NaN,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,1.0,1.0,1.000000e+00
5568,102956.0,2.0,NaN,2.0,NaN,1.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,NaN,NaN,1.000000e+00

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## RXQ_RX_J (Prescription Medications)

In [13]:
df = catalog.load("rxq_rx_j_dataset")
df

                    INFO     Loading data from rxq_rx_j_dataset (GenericDataset)...            ]8;id=13771128;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=13771129;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,RXDUSE,RXDDRUG,RXDDRGID,RXQSEEN,RXDDAYS,RXDRSC1,RXDRSC2,RXDRSC3,RXDRSD1,RXDRSD2,RXDRSD3,RXDCOUNT
0,93703.0,2.0,b'',b'',NaN,NaN,b'',b'',b'',b'',b'',b'',NaN
1,93704.0,2.0,b'',b'',NaN,NaN,b'',b'',b'',b'',b'',b'',NaN
2,93705.0,1.0,b'ENALAPRIL; HYDROCHLOROTHIAZIDE',b'd03740',1.0,5475.0,b'I10',b'',b'',b'Essential (primary) hypertension',b'',b'',3.0
3,93705.0,1.0,b'MELOXICAM',b'd04532',1.0,61.0,b'M06.9',b'',b'',"b'Rheumatoid arthritis, unspecified'",b'',b'',3.0
4,93705.0,1.0,b'OMEPRAZOLE',b'd00325',1.0,3650.0,b'R12',b'',b'',b'Heartburn',b'',b'',3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19638,102956.0,1.0,b'CETIRIZINE',b'd03827',1.0,4.0,b'T78.40',b'',b'',"b'Allergy, unspecified'",b'',b'',5.0
19639,102956.0,1.0,b'DULOXETINE',b'd05355',1.0,365.0,b'F41.9',b'M79.2',b'',"b'Anxiety disorder, unspecified'","b'Neuralgia and neuritis, unspecified'",b'',5.0
19640,102956.0,1.0,b'FLUTICASONE NASAL',b'd04283',1.0,4.0,b'J30.2',b'',b'',b'Other seasonal allergic rhinitis',b'',b'',5.0
19641,102956.0,1.0,b'GABAPENTIN',b'd03182',1.0,365.0,b'M79.2',b'',b'',"b'Neuralgia and neuritis, unspecified'",b'',b'',5.0
19642,102956.0,1.0,b'NORTRIPTYLINE',b'd00144',1.0,365.0,b'M79.2',b'',b'',"b'Neuralgia and neuritis, unspecified'",b'',b'',5.0

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## WHQ_J (Weight History)

In [14]:
df = catalog.load("whq_j_dataset")
df

[06/05/26 14:47:16] INFO     Loading data from whq_j_dataset (GenericDataset)...               ]8;id=13771134;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=13771135;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,WHD010,WHD020,WHQ030,WHQ040,WHD050,WHQ060,WHQ070,WHD080A,WHD080B,...,WHD080U,WHD080L,WHQ225,WHD110,WHD120,WHD130,WHD140,WHQ150,WHQ190,WHQ200
0,93705.0,63.0,165.0,1.0,3.0,165.0,NaN,2.0,NaN,NaN,...,NaN,NaN,4.0,150.0,130.0,63.0,170.0,62.0,2.0,NaN
1,93706.0,68.0,145.0,3.0,3.0,145.0,NaN,2.0,NaN,NaN,...,NaN,NaN,5.0,NaN,NaN,NaN,150.0,17.0,2.0,NaN
2,93708.0,60.0,118.0,3.0,3.0,118.0,NaN,2.0,NaN,NaN,...,NaN,NaN,5.0,118.0,100.0,60.0,120.0,40.0,2.0,NaN
3,93709.0,62.0,200.0,1.0,2.0,190.0,NaN,2.0,NaN,NaN,...,NaN,NaN,3.0,170.0,160.0,62.0,200.0,50.0,2.0,NaN
4,93711.0,69.0,142.0,2.0,3.0,142.0,NaN,2.0,NaN,NaN,...,NaN,NaN,5.0,142.0,148.0,69.0,152.0,33.0,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6156,102950.0,68.0,185.0,1.0,2.0,185.0,NaN,2.0,NaN,NaN,...,NaN,NaN,5.0,160.0,145.0,68.0,200.0,45.0,2.0,NaN
6157,102952.0,NaN,117.0,3.0,3.0,117.0,NaN,2.0,NaN,NaN,...,NaN,NaN,5.0,117.0,120.0,NaN,120.0,23.0,2.0,NaN
6158,102953.0,65.0,218.0,1.0,2.0,205.0,NaN,2.0,NaN,NaN,...,NaN,NaN,5.0,200.0,180.0,NaN,222.0,41.0,2.0,NaN
6159,102954.0,66.0,150.0,3.0,3.0,180.0,2.0,2.0,NaN,NaN,...,NaN,NaN,5.0,145.0,120.0,NaN,180.0,38.0,2.0,NaN
6160,102956.0,69.0,250.0,1.0,2.0,245.0,NaN,2.0,NaN,NaN,...,NaN,NaN,1.0,240.0,220.0,NaN,255.0,34.0,2.0,NaN

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## DLQ_J (Disability)

In [15]:
df = catalog.load("dlq_j_dataset")
df

                    INFO     Loading data from dlq_j_dataset (GenericDataset)...               ]8;id=13771140;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=13771141;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,DLQ010,DLQ020,DLQ040,DLQ050,DLQ060,DLQ080,DLQ100,DLQ110,DLQ130,DLQ140,DLQ150,DLQ170
0,93703.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93704.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93705.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,2.0,1.0,4.0,2.0,1.0
3,93706.0,2.0,2.0,2.0,2.0,2.0,2.0,5.0,2.0,NaN,5.0,2.0,NaN
4,93707.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8892,102952.0,2.0,2.0,2.0,2.0,2.0,2.0,5.0,2.0,NaN,5.0,2.0,NaN
8893,102953.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,2.0,3.0,4.0,2.0,1.0
8894,102954.0,2.0,2.0,2.0,2.0,2.0,2.0,5.0,2.0,NaN,5.0,2.0,NaN
8895,102955.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8896,102956.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,3.0,1.0,1.0

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)