In [ ]:
%load_ext kedro.ipython

In [ ]:
import pandas as pd

## Audiometry — AUX_J

In [1]:
aux = catalog.load("aux_j_dataset")
aux.head()

[06/01/26 16:11:21] INFO     Loading data from aux_j_dataset (GenericDataset)...               ]8;id=3103598;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=3103599;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,AUAEXSTS,AUAEXCMT,AUQ011,AUQ540,AUQ550,AUQ550A,AUQ550B,AUQ550C,AUQ550D,...,AUXR1K2L,AUXR2KL,AUXR3KL,AUXR4KL,AUXR6KL,AUXR8KL,AUAREQC,AUATYMTR,AUALEQC,AUATYMTL
0,93706.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,b'Type A',1.0,b'Type A'
1,93707.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,b'Type A',1.0,b'Type A'
2,93709.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,b'Type A',1.0,b'Type A'
3,93712.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,b'Type A',1.0,b'Type A'
4,93715.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,60.0,NaN,NaN,NaN,NaN,2.0,b'Type A',2.0,b'Type A'

## Audiometry - Acoustic Reflex — AUXAR_J

In [ ]:
auxar = catalog.load("auxar_j_dataset")
auxar.head()

## Audiometry - Tympanometry — AUXTYM_J

In [ ]:
auxtym = catalog.load("auxtym_j_dataset")
auxtym.head()

## Audiometry - Wideband Reflectance — AUXWBR_J

In [ ]:
auxwbr = catalog.load("auxwbr_j_dataset")
auxwbr.head()

## Body Measures — BMX_J

In [ ]:
bmx = catalog.load("bmx_j_dataset")
bmx.head()

## Blood Pressure — BPX_J

In [ ]:
bpx = catalog.load("bpx_j_dataset")
bpx.head()

## Blood Pressure - Oscillometric — BPXO_J

In [ ]:
bpxo = catalog.load("bpxo_j_dataset")
bpxo.head()

## DXA - Whole Body — DXX_J

In [ ]:
dxx = catalog.load("dxx_j_dataset")
dxx.head()

## DXA - Android/Gynoid — DXXAG_J

In [ ]:
dxxag = catalog.load("dxxag_j_dataset")
dxxag.head()

## DXA - Femur — DXXFEM_J

In [ ]:
dxxfem = catalog.load("dxxfem_j_dataset")
dxxfem.head()

## DXA - Spine — DXXSPN_J

In [ ]:
dxxspn = catalog.load("dxxspn_j_dataset")
dxxspn.head()

## Oral Health - Dentition — OHXDEN_J

In [ ]:
ohxden = catalog.load("ohxden_j_dataset")
ohxden.head()

## Oral Health - Recommendation of Care — OHXREF_J

In [2]:
ohxref = catalog.load("ohxref_j_dataset")
ohxref.head()

[06/01/26 16:11:37] INFO     Loading data from ohxref_j_dataset (GenericDataset)...            ]8;id=3103604;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=3103605;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,OHDEXSTS,OHDRCSTS,OHAREC,OHAROCDT,OHAROCGP,OHAROCOH,OHAROCCI,OHAROCDE,OHARNF,OHAROTH,OHAPOS
0,93703.0,1.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
1,93704.0,1.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
2,93705.0,1.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
3,93706.0,1.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
4,93707.0,1.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0